-- Clear the legacy plaintext refresh tokens from staff.refresh_token.
--
-- The column held signed JWT refresh tokens in plaintext, one per account.
-- Migration 0001 moved refresh tokens to the `sessions` table as opaque
-- strings stored only as sha256(realm + ":" + token), and nothing reads
-- staff.refresh_token any more.
--
-- The COLUMN is deliberately kept: dropping it is the only irreversible step
-- in this release, and keeping it means a code rollback still finds the schema
-- it expects. But keeping the column is not a reason to keep the VALUES —
-- those are live credential material sitting at rest for no purpose.
--
-- Rollback stays safe and symmetric: afterwards the old code finds no matching
-- token and staff re-authenticate, which they must do rolling forward anyway.
UPDATE "staff" SET "refresh_token" = NULL WHERE "refresh_token" IS NOT NULL;
