CREATE TYPE "sman"."audit_actor_type" AS ENUM('staff', 'customer', 'system');--> statement-breakpoint
CREATE TABLE "sman"."truck_extras" (
	"truck_id" bigint PRIMARY KEY NOT NULL,
	"vin" varchar(50) DEFAULT '',
	"year" integer,
	"truck_type" varchar(50) DEFAULT '',
	"fuel_level" integer DEFAULT 100,
	"registration_expiry" date,
	"next_service_mileage" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sman"."audit_logs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sman"."audit_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"entity_type" varchar(32) NOT NULL,
	"entity_id" integer NOT NULL,
	"action" varchar(64) NOT NULL,
	"prev_state" varchar(32),
	"new_state" varchar(32),
	"actor_type" "sman"."audit_actor_type" NOT NULL,
	"actor_staff_id" bigint,
	"actor_customer_id" bigint,
	"metadata" jsonb,
	"ip_address" varchar(64),
	"user_agent" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "audit_logs_actor_arc_check" CHECK (("sman"."audit_logs"."actor_type" = 'staff'    AND "sman"."audit_logs"."actor_staff_id"    IS NOT NULL AND "sman"."audit_logs"."actor_customer_id" IS NULL)
       OR ("sman"."audit_logs"."actor_type" = 'customer' AND "sman"."audit_logs"."actor_customer_id" IS NOT NULL AND "sman"."audit_logs"."actor_staff_id"    IS NULL)
       OR ("sman"."audit_logs"."actor_type" = 'system'   AND "sman"."audit_logs"."actor_staff_id"    IS NULL     AND "sman"."audit_logs"."actor_customer_id" IS NULL))
);
--> statement-breakpoint
CREATE TABLE "sman"."audit_events" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sman"."audit_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"action" varchar(100) NOT NULL,
	"actor_type" "sman"."audit_actor_type" DEFAULT 'system' NOT NULL,
	"actor_id" integer,
	"actor_name" varchar(255) DEFAULT '',
	"entity_type" varchar(100) DEFAULT '',
	"entity_id" varchar(64) DEFAULT '',
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "sman"."truck_extras" ADD CONSTRAINT "truck_extras_truck_id_consumer_fleettruck_id_fk" FOREIGN KEY ("truck_id") REFERENCES "public"."consumer_fleettruck"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sman"."audit_logs" ADD CONSTRAINT "audit_logs_actor_staff_id_administration_user_id_fk" FOREIGN KEY ("actor_staff_id") REFERENCES "public"."administration_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sman"."audit_logs" ADD CONSTRAINT "audit_logs_actor_customer_id_consumer_customer_id_fk" FOREIGN KEY ("actor_customer_id") REFERENCES "public"."consumer_customer"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "audit_logs_entity_idx" ON "sman"."audit_logs" USING btree ("entity_type","entity_id","created_at");--> statement-breakpoint
CREATE INDEX "audit_logs_actor_staff_idx" ON "sman"."audit_logs" USING btree ("actor_staff_id","created_at") WHERE "sman"."audit_logs"."actor_staff_id" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "audit_events_entity_idx" ON "sman"."audit_events" USING btree ("entity_type","entity_id");--> statement-breakpoint
CREATE INDEX "audit_events_action_idx" ON "sman"."audit_events" USING btree ("action");--> statement-breakpoint
CREATE INDEX "audit_events_created_idx" ON "sman"."audit_events" USING btree ("created_at");